# Generated by Django 4.2.7 on 2023-12-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreInventory', '0002_alter_author_id_alter_publisher_id_alter_shipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_column='id', to='BookstoreInventory.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='BookstoreInventory.publisher'),
        ),
    ]
