# Generated by Django 4.2.7 on 2023-12-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreInventory', '0003_alter_book_authors_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_column='author_ids', to='BookstoreInventory.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.CASCADE, to='BookstoreInventory.publisher'),
        ),
    ]
