# Generated by Django 4.2.7 on 2023-12-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreInventory', '0004_alter_book_authors_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='middle_name',
        ),
    ]
