# Generated by Django 4.2.7 on 2023-12-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreInventory', '0005_remove_transaction_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='book_isbn',
        ),
        migrations.AddField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', null=True, on_delete=django.db.models.deletion.CASCADE, to='BookstoreInventory.book'),
        ),
    ]
