# Generated by Django 4.2.7 on 2023-12-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreInventory', '0007_remove_transaction_book_transaction_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='default.png', upload_to='profile'),
        ),
    ]
